//supermutants
#define LOADOUT_CATEGORY_SMUTANT	"Muties"
#define LOADOUT_SUBCATEGORY_SMUTANT_GENERAL	"General"
#define LOADOUT_SUBCATEGORY_SMUTANT_SHOES	"Shoes"
#define LOADOUT_SUBCATEGORY_SMUTANT_UNIFORM	"Uniform"
#define LOADOUT_SUBCATEGORY_SMUTANT_GLOVES	"Gloves"
#define LOADOUT_SUBCATEGORY_SMUTANT_SUIT	"Suit"
#define LOADOUT_SUBCATEGORY_SMUTANT_HATS	"Headwear"
